export const mainBGColor = '#f7f7f7';
export const buttonCompressed = '#c7c7c7'
export const noColor = 'rgba(0, 0, 0, 0.0)'
export const headerBGColor = '#f4f3f2';
export const guitarBGColor = 'red';
export const neckColor = '#a36233';
export const fretColor = 'black';
export const stringColor = '#ffffff';
export const emptyNoteColor = 'rgba(168, 193, 221, 0.8)'
